sudo: required
services: 
  - docker

before_install:
  - docker build -t josephkeenan82/docker-react -f Dockerfile.dev .

script:
  - docker run josephkeenan82/docker-react npm run test -- --coverage