sudo: required
services: 
  - docker

before_install:
  - docker build -t josephkeenan82/docker-react -f Dockerfile.dev .

script:
  - docker run josephkeenan82/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-777834440342"
  bucket_path: "docker-react"
  on:
    brnach: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
